version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.3.1
  rust: shadesmar/rust@dev:alpha

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  with_rust_test:
    executor: rust/rust
    steps:
      - checkout
      - run:
          command: |
            {
              echo '[toolchain]'
              echo 'channel = "1.86.0"'
              echo 'components = [ "rustfmt", "clippy" ]'
            } >> rust-toolchain.toml
      - rust/with_rust:
          steps:
            - run:
                command: |
                  cargo --version
                  cargo new hello
                  cd hello
                  cargo run

workflows:
  version: 2
  test-deploy:
    jobs:
      - with_rust_test:
          filters: *filters
          context: [aws]
          
      - orb-tools/pack:
          filters: *release-filters
          context: [aws]

      - orb-tools/publish:
          orb_name: shadesmar/rust
          vcs_type: github
          pub_type: production
          requires:
            - orb-tools/pack
            - with_rust_test
          filters: *release-filters
          context: [aws]
