version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.3
  <orb-name>: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  integration-test-1:
    executor: shadesmar/rust
    steps:
      - checkout
      - run:
          command: |
            {
              echo '[toolchain]'
              echo 'channel = "1.55.0"'
              echo 'components = [ "rustfmt", "clippy" ]'
            } >> rust-toolchain.toml
      - shadesmar/with_rust:
          steps:
            - run:
                command: |
                  cargo --version
                  cargo new hello
                  cd hello
                  cargo run
workflows:
  test-deploy:
    jobs:
      - integration-test-1:
          filters: *filters
          
      - orb-tools/pack:
          filters: *release-filters

      - orb-tools/publish:
          orb_name: shadesmar/rust
          vcs_type: github
          pub_type: production
          requires:
            - orb-tools/pack
            - integration-test-1
          context: [aws]
          filters: *release-filters
