jobs:
  integration-test-1:
    executor: shadesmar/rust
    steps:
      - checkout
      - run:
          command: |
            {
              echo '[toolchain]'
              echo 'channel = "1.55.0"'
              echo 'components = [ "rustfmt", "clippy" ]'
            } >> rust-toolchain.toml
      - bearcove/with-rust:
          steps:
            - run:
                command: |
                  cargo --version
                  cargo new hello
                  cd hello
                  cargo run
